def fix_notifications(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # We define replacement blocks
    replacements = [
        # 1. onNewTrainingCreated
        (
            """                // Prepare FCM message if user has a token\n                if (fcmToken) {\n                    notifications.push({\n                        token: fcmToken,\n                        notification: {\n                            title: notifTitle,\n                            body: post?.title || notifBodyDefault,\n                        },\n                        data: {\n                            type: notifType,\n                            resourceId: postId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                }""",
            """                // Prepare FCM message if user has a token\n                const userTokens = userData.fcmTokens || (fcmToken ? [fcmToken] : []);\n                userTokens.forEach((token: string) => {\n                    notifications.push({\n                        token: token,\n                        notification: {\n                            title: notifTitle,\n                            body: post?.title || notifBodyDefault,\n                        },\n                        data: {\n                            type: notifType,\n                            resourceId: postId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                });"""
        ),
        # 2. onNewBadgeCreated
        (
            """                // Prepare FCM message if user has a token\n                if (fcmToken) {\n                    notifications.push({\n                        token: fcmToken,\n                        notification: {\n                            title: "Nouveau badge disponible !",\n                            body:\n                                badge.name ||\n                                "Un nouveau badge vient d'être lancé",\n                        },\n                        data: {\n                            type: "newBadge",\n                            resourceId: badgeId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                }""",
            """                // Prepare FCM message if user has a token\n                const userTokens = userData.fcmTokens || (fcmToken ? [fcmToken] : []);\n                userTokens.forEach((token: string) => {\n                    notifications.push({\n                        token: token,\n                        notification: {\n                            title: "Nouveau badge disponible !",\n                            body:\n                                badge.name ||\n                                "Un nouveau badge vient d'être lancé",\n                        },\n                        data: {\n                            type: "newBadge",\n                            resourceId: badgeId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                });"""
        ),
        # 3. onUserBadgeAwarded
        (
            """            const userData = userDoc.data();\n            const fcmToken = userData?.fcmToken;""",
            """            const userData = userDoc.data();\n            const fcmTokens: string[] = userData?.fcmTokens || (userData?.fcmToken ? [userData?.fcmToken] : []);"""
        ),
        # 4. onUserBadgeAwarded (Send FCM)
        (
            """            // Send FCM notification if user has a token\n            if (fcmToken) {\n                await admin.messaging().send({\n                    token: fcmToken,\n                    notification: {\n                        title: "Félicitations ! 🎉",\n                        body: notificationBody,\n                    },\n                    data: {\n                        type: "achievement",\n                        resourceId: badgeId,\n                        click_action: "FLUTTER_NOTIFICATION_CLICK",\n                    },\n                    android: {\n                        priority: "high",\n                        notification: {\n                            channelId: "novopharma_channel",\n                            sound: "default",\n                        },\n                    },\n                    apns: {\n                        payload: {\n                            aps: {\n                                sound: "default",\n                                badge: 1,\n                            },\n                        },\n                    },\n                });\n            }""",
            """            // Send FCM notifications to all user tokens\n            if (fcmTokens.length > 0) {\n                const messages = fcmTokens.map((token) => ({\n                    token: token,\n                    notification: {\n                        title: "Félicitations ! 🎉",\n                        body: notificationBody,\n                    },\n                    data: {\n                        type: "achievement",\n                        resourceId: badgeId,\n                        click_action: "FLUTTER_NOTIFICATION_CLICK",\n                    },\n                    android: {\n                        priority: "high" as const,\n                        notification: {\n                            channelId: "novopharma_channel",\n                            sound: "default",\n                        },\n                    },\n                    apns: {\n                        payload: {\n                            aps: {\n                                sound: "default",\n                                badge: 1,\n                            },\n                        },\n                    },\n                }));\n                await admin.messaging().sendEach(messages);\n            }"""
        ),
        # 5. onUserBadgeAwarded (Admins)
        (
            """                    if (adminData.fcmToken) {\n                        adminNotifications.push({\n                            token: adminData.fcmToken,\n                            notification: {\n                                title: adminTitle,\n                                body: adminBody,\n                            },\n                            data: {\n                                type: "achievement",\n                                resourceId: badgeId,\n                                click_action: "FLUTTER_NOTIFICATION_CLICK",\n                            },\n                        });\n                    }""",
            """                    const adminTokens: string[] = adminData.fcmTokens || (adminData.fcmToken ? [adminData.fcmToken] : []);\n                    adminTokens.forEach((token) => {\n                        adminNotifications.push({\n                            token: token,\n                            notification: {\n                                title: adminTitle,\n                                body: adminBody,\n                            },\n                            data: {\n                                type: "achievement",\n                                resourceId: badgeId,\n                                click_action: "FLUTTER_NOTIFICATION_CLICK",\n                            },\n                        });\n                    });"""
        ),
        # 6. onNewGoalCreated
        (
            """                // Prepare FCM message if user has a token\n                if (fcmToken) {\n                    notifications.push({\n                        token: fcmToken,\n                        notification: {\n                            title: "Nouvel objectif disponible !",\n                            body: goal.description ||\n                                "Un nouvel objectif a été ajouté",\n                        },\n                        data: {\n                            type: "newGoal",\n                            resourceId: goalId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                }""",
            """                // Prepare FCM message if user has a token\n                const userTokens: string[] = userData.fcmTokens || (fcmToken ? [fcmToken] : []);\n                userTokens.forEach((token) => {\n                    notifications.push({\n                        token: token,\n                        notification: {\n                            title: "Nouvel objectif disponible !",\n                            body: goal.description ||\n                                "Un nouvel objectif a été ajouté",\n                        },\n                        data: {\n                            type: "newGoal",\n                            resourceId: goalId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                });"""
        ),
        # 7. onUserGoalCompleted
        (
            """                const userData = userDoc.data();\n                const fcmToken = userData?.fcmToken;""",
            """                const userData = userDoc.data();\n                const fcmTokens: string[] = userData?.fcmTokens || (userData?.fcmToken ? [userData?.fcmToken] : []);"""
        ),
        # 8. onUserGoalCompleted (Send FCM)
        (
            """                // Send FCM notification if user has a token\n                if (fcmToken) {\n                    await admin.messaging().send({\n                        token: fcmToken,\n                        notification: {\n                            title: "Objectif atteint ! 🎉",\n                            body: notificationBody,\n                        },\n                        data: {\n                            type: "goalCompleted",\n                            resourceId: goalId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                        android: {\n                            priority: "high",\n                            notification: {\n                                channelId: "novopharma_channel",\n                                sound: "default",\n                            },\n                        },\n                        apns: {\n                            payload: {\n                                aps: {\n                                    sound: "default",\n                                    badge: 1,\n                                },\n                            },\n                        },\n                    });\n                }""",
            """                // Send FCM notification to all devices\n                if (fcmTokens.length > 0) {\n                    const messages = fcmTokens.map((token) => ({\n                        token: token,\n                        notification: {\n                            title: "Objectif atteint ! 🎉",\n                            body: notificationBody,\n                        },\n                        data: {\n                            type: "goalCompleted",\n                            resourceId: goalId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                        android: {\n                            priority: "high" as const,\n                            notification: {\n                                channelId: "novopharma_channel",\n                                sound: "default",\n                            },\n                        },\n                        apns: {\n                            payload: {\n                                aps: {\n                                    sound: "default",\n                                    badge: 1,\n                                },\n                            },\n                        },\n                    }));\n                    await admin.messaging().sendEach(messages);\n                }"""
        ),
        # 9. onUserGoalCompleted (Admins)
        (
            """                        if (adminData.fcmToken) {\n                            adminNotifications.push({\n                                token: adminData.fcmToken,\n                                notification: {\n                                    title: adminTitle,\n                                    body: adminBody,\n                                },\n                                data: {\n                                    type: "goalCompleted",\n                                    resourceId: goalId,\n                                    click_action: "FLUTTER_NOTIFICATION_CLICK",\n                                },\n                            });\n                        }""",
            """                        const adminTokens: string[] = adminData.fcmTokens || (adminData.fcmToken ? [adminData.fcmToken] : []);\n                        adminTokens.forEach((token) => {\n                            adminNotifications.push({\n                                token: token,\n                                notification: {\n                                    title: adminTitle,\n                                    body: adminBody,\n                                },\n                                data: {\n                                    type: "goalCompleted",\n                                    resourceId: goalId,\n                                    click_action: "FLUTTER_NOTIFICATION_CLICK",\n                                },\n                            });\n                        });"""
        ),
        # 10. sendReminderNotifications
        (
            """                if (fcmToken) {\n                    notifications.push({\n                        token: fcmToken,\n                        notification: {title, body},\n                        data: {\n                            type: itemType, resourceId: itemId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                }""",
            """                const userTokens: string[] = userData.fcmTokens || (fcmToken ? [fcmToken] : []);\n                userTokens.forEach((token) => {\n                    notifications.push({\n                        token: token,\n                        notification: {title, body},\n                        data: {\n                            type: itemType, resourceId: itemId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                });"""
        ),
        # 11. onNewCustomNotificationCreated
        (
            """                if (fcmToken) {\n                    notifications.push({\n                        token: fcmToken,\n                        notification: {\n                            title: notifMsg.title,\n                            body: notifMsg.description,\n                        },\n                        data: {\n                            type: "customNotification",\n                            resourceId: docId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                }""",
            """                const userTokens: string[] = userData.fcmTokens || (fcmToken ? [fcmToken] : []);\n                userTokens.forEach((token) => {\n                    notifications.push({\n                        token: token,\n                        notification: {\n                            title: notifMsg.title,\n                            body: notifMsg.description,\n                        },\n                        data: {\n                            type: "customNotification",\n                            resourceId: docId,\n                            click_action: "FLUTTER_NOTIFICATION_CLICK",\n                        },\n                    });\n                });"""
        )
    ]

    for (old_text, new_text) in replacements:
        if old_text in content:
            content = content.replace(old_text, new_text)
            print("Successfully replaced a block.")
        else:
            print("Failed to find a block!")
            print("Looking for:")
            print(old_text)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

fix_notifications("C:/Users/imadb/Desktop/Apeiron Technologies/novoPharma/novopharma-mychallenge-mobile/functions/src/notifications.ts")
